In [22]:
from vpython import *
import numpy as np
import random

# Initial Langton's Ant Simulation Verification

## Functions

In [23]:
# Function to draw matrix
def draw_matrix(matrix):
    y = 0
    for i in range(len(matrix)):
        x = 0
        for j in range(len(matrix[i])):
            cell = box(pos = vector(x, y, 0), size = vector(1,1,1))
            if matrix[i][j] == 0:
                cell.color = color.white
            elif matrix[i][j] == 1:
                cell.color = color.red
                
            x += 1.25
            
        y -= 1.25

In [32]:
# Function to update matrix given game of life rules
def update_matrix(matrix, pos, direction):
    new_mat = matrix
    new_pos = pos
    new_direction = direction
    
    cur_value = new_mat[pos[0], pos[1]]
    
    # update direction
    if cur_value == 0:
        # rotate right
        new_direction = (new_direction + 1) % 4
        # update matrix
        new_mat[pos[0], pos[1]] = 1
    else:
        # rotate left
        new_direction = (new_direction - 1) % 4
        # update matrix
        new_mat[pos[0], pos[1]] = 0       

    
    # move pos based on direction
    if new_direction == 0:
        new_pos[0] = (new_pos[0] - 1) % new_mat.shape[0]
    elif new_direction == 1:
        new_pos[1] = (new_pos[1] + 1) % new_mat.shape[1]
    elif new_direction == 2:
        new_pos[0] = (new_pos[0] + 1) % new_mat.shape[0]
    elif new_direction == 3:
        new_pos[1] = (new_pos[1] - 1) % new_mat.shape[1]
    
    return (new_mat, new_pos, new_direction)

## Simulation of Emergent Behaviors

### Simplicity

In [6]:
scene = canvas()

# initialize values
row = 10; col = 10
matrix = np.zeros((row, col))
pos = [random.randint(0, row-1), random.randint(0, col-1)]
direction = 0

# draw
draw_matrix(matrix)

num_steps = 1000

# Main loop
for i in range(num_steps):
    rate(20)
    # update
    matrix, pos, direction = update_matrix(matrix, pos, direction)
    # draw
    draw_matrix(matrix)

<IPython.core.display.Javascript object>

### Chaos - long run time

In [6]:
scene = canvas()

# initialize values
row = 10; col = 10
matrix = np.zeros((row, col))
pos = [random.randint(0, row-1), random.randint(0, col-1)]
direction = 0

# draw
draw_matrix(matrix)

num_steps = 20000

# Main loop
for i in range(num_steps):
    # update
    matrix, pos, direction = update_matrix(matrix, pos, direction)
    # draw
    draw_matrix(matrix)

<IPython.core.display.Javascript object>

### Emergent (Highway) - VERY long run time

In [ ]:
scene = canvas()

# initialize values
row = 10; col = 10
matrix = np.zeros((row, col))
pos = [random.randint(0, row-1), random.randint(0, col-1)]
direction = 0

# draw
draw_matrix(matrix)

num_steps = 50000

# Main loop
for i in range(num_steps):
    # update
    matrix, pos, direction = update_matrix(matrix, pos, direction)
    # draw
    draw_matrix(matrix)

# User Input for Message and Key

In [25]:
# Input message
m_row = 10; m_col = 10
message_matrix = np.random.randint(2, size=(m_row, m_col))

# Key
# User values
key_obstacles = [[3, 6], [7, 2], [3, 1], [0, 9], [7, 2]]
key_iterations = 3000
key_direction = 2 # 0 to 3
key_position = [4, 2]

# Encryption

In [26]:
obstacles = key_obstacles
iterations = key_iterations
direction = key_direction
position = key_position

key_matrix = np.zeros((m_row, m_col))
# Set the obstacles indices to 1 in the matrix
for i, j in obstacles:
    key_matrix[i][j] = 1

# Key creation
for i in range(iterations):
    # update
    key_matrix, position, direction = update_matrix(key_matrix, position, direction)


# Encryption
key_matrix = key_matrix.astype(int)
encrypted_matrix = np.bitwise_xor(message_matrix, key_matrix)


# Decryption

In [33]:
obstacles = key_obstacles
iterations = key_iterations
direction = key_direction
position = key_position

key_matrix = np.zeros((m_row, m_col))
# Set the obstacles indices to 1 in the matrix
for i, j in obstacles:
    key_matrix[i][j] = 1

# Key creation
for i in range(iterations):
    # update
    key_matrix, position, direction = update_matrix(key_matrix, position, direction)

# Decryption
key_matrix = key_matrix.astype(int)
decrypted_message = np.bitwise_xor(encrypted_matrix, key_matrix)

# Verification

In [37]:
assert(decrypted_message.all() == message_matrix.all())

# Changing key slightly and attempt decryption

In [38]:
obstacles = key_obstacles
iterations = key_iterations
direction = (key_direction + 1) % 4
position = key_position

key_matrix = np.zeros((m_row, m_col))
# Set the obstacles indices to 1 in the matrix
for i, j in obstacles:
    key_matrix[i][j] = 1

# Key creation
for i in range(iterations):
    # update
    key_matrix, position, direction = update_matrix(key_matrix, position, direction)

# Decryption
key_matrix = key_matrix.astype(int)
decrypted_message = np.bitwise_xor(encrypted_matrix, key_matrix)

# Verification

In [40]:
assert(decrypted_message.all() != message_matrix.all())

AssertionError: 

In [43]:
print(message_matrix)
print(decrypted_message)

[[0 0 1 1 0 0 1 0 1 1]
 [0 1 0 1 0 1 1 1 0 0]
 [0 1 1 0 1 0 1 1 0 1]
 [0 0 0 1 1 1 0 1 0 0]
 [1 0 0 1 1 1 1 0 1 0]
 [0 1 0 1 0 1 1 1 0 1]
 [1 1 0 0 0 1 0 1 0 0]
 [0 0 0 1 0 0 1 1 0 0]
 [0 1 1 1 1 1 0 0 0 1]
 [0 0 0 0 1 0 0 0 1 0]]
[[1 0 1 1 1 1 0 1 0 1]
 [0 1 1 1 0 0 1 0 0 1]
 [1 1 0 1 1 0 0 1 0 1]
 [1 0 1 0 0 0 0 1 0 1]
 [1 0 0 0 1 0 0 1 1 0]
 [0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 0 0]
 [0 0 0 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 1 0 0]
 [1 1 0 0 0 0 1 1 0 0]]


As show, the matrices are very differnt